<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Mermer.Core.Couch</AssemblyName>
    <RootNamespace>Mermer.Core.Couch</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Changes\DesignDocs\changes.json" />
    <None Remove="Changes\DesignDocs\synchronizer-doc.json" />
    <None Remove="Changes\Functions\changes-by-doc-map.js" />
    <None Remove="Changes\Functions\synchronizer-indexes-map.js" />
    <None Remove="Changes\Functions\synchronizer-indexes-reduce.js" />
    <None Remove="Commerce\DesignDocs\commerce-reporting.json" />
    <None Remove="Commerce\DesignDocs\commerce.json" />
    <None Remove="Commerce\Functions\invoice-infos-map.js" />
    <None Remove="Commerce\Functions\invoice-payments-map.js" />
    <None Remove="Commerce\Functions\last-purchase-prices-map.js" />
    <None Remove="Commerce\Functions\last-purchase-prices-reduce.js" />
    <None Remove="Common\DesignDocs\common.json" />
    <None Remove="Common\Functions\common-facets-reduce.js" />
    <None Remove="Common\Functions\common-revisions-map.js" />
    <None Remove="CRM\DesignDocs\crm.json" />
    <None Remove="CRM\Functions\partner-actions-map.js" />
    <None Remove="CRM\Functions\partner-balances-by-office-and-id-map.js" />
    <None Remove="CRM\Functions\partner-balances-by-office-map.js" />
    <None Remove="CRM\Functions\partner-balances-partial-invoices.js" />
    <None Remove="CRM\Functions\partner-balances-partial-others.js" />
    <None Remove="CRM\Functions\partner-balances-reduce.js" />
    <None Remove="CRM\Functions\partner-facets-map.js" />
    <None Remove="Enterprise\DesignDocs\enterprise.json" />
    <None Remove="Enterprise\Functions\depository-facets-map.js" />
    <None Remove="Enterprise\Functions\office-facets-map.js" />
    <None Remove="Enterprise\Functions\warehouse-facets-map.js" />
    <None Remove="Finance\Spending\DesignDocs\finance-spending.json" />
    <None Remove="Finance\Spending\Functions\expense-actions-map.js" />
    <None Remove="Finance\Spending\Functions\expense-facets-map.js" />
    <None Remove="FundsManagement\DesignDocs\funds-management.json" />
    <None Remove="FundsManagement\Functions\funds-actions-map.js" />
    <None Remove="FundsManagement\Functions\funds-balances-map.js" />
    <None Remove="FundsManagement\Functions\funds-balances-reduce.js" />
    <None Remove="StockManagement\DesignDocs\stock-management-reporting.json" />
    <None Remove="StockManagement\DesignDocs\stock-management.json" />
    <None Remove="StockManagement\Functions\stock-actions-by-warehouse-all-map.js" />
    <None Remove="StockManagement\Functions\stock-actions-by-warehouse-and-id-all-map.js" />
    <None Remove="StockManagement\Functions\stock-actions-by-warehouse-and-id-map.js" />
    <None Remove="StockManagement\Functions\stock-actions-by-warehouse-map.js" />
    <None Remove="StockManagement\Functions\stock-actions-map.js" />
    <None Remove="StockManagement\Functions\stock-actions-partial-consts.js" />
    <None Remove="StockManagement\Functions\stock-actions-partial-others.js" />
    <None Remove="StockManagement\Functions\stock-actions-partial-overheads.js" />
    <None Remove="StockManagement\Functions\stock-actions-partial-transfer-destination.js" />
    <None Remove="StockManagement\Functions\stock-actions-partial-transfer-source.js" />
    <None Remove="StockManagement\Functions\stock-alternatives-map.js" />
    <None Remove="StockManagement\Functions\stock-balances-by-warehouse-and-id-map.js" />
    <None Remove="StockManagement\Functions\stock-balances-by-warehouse-map.js" />
    <None Remove="StockManagement\Functions\stock-balances-reduce.js" />
    <None Remove="StockManagement\Functions\stock-facets-map.js" />
    <None Remove="StockManagement\Functions\stock-info-map.js" />
    <None Remove="StockManagement\Functions\stock-repricing-map.js" />
    <None Remove="StockManagement\Functions\stock-tracking-by-lineId-map.js" />
    <None Remove="StockManagement\Functions\stock-tracking-by-lineSourceId-map.js" />
    <None Remove="StockManagement\Functions\stock-tracking-by-transactionId-map.js" />
    <None Remove="StockManagement\Functions\stock-tracking-map.js" />
    <None Remove="StockManagement\Functions\stock-tracking-partial-consts.js" />
    <None Remove="StockManagement\Functions\stock-tracking-partial-transfer-destination.js" />
    <None Remove="StockManagement\Functions\stock-tracking-partial-transfer-source.js" />
    <None Remove="StockManagement\Functions\stock-turnovers-map.js" />
    <None Remove="StockManagement\Functions\stock-turnovers-reduce.js" />
    <None Remove="StockManagement\Indexes\bucket-info.json" />
    <None Remove="StockManagement\Indexes\stock-search-fts.json" />
    <None Remove="Transactions\DesignDocs\transaction.json" />
    <None Remove="Transactions\Functions\transaction-facets-map.js" />
    <None Remove="Transactions\Functions\transaction-list-map.js" />
    <None Remove="Warehousing\Ordering\DesignDocs\warehousing-ordering.json" />
    <None Remove="Warehousing\Ordering\Functions\stock-orders-map.js" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Changes\DesignDocs\changes.json" />
    <EmbeddedResource Include="Changes\DesignDocs\synchronizer-doc.json" />
    <EmbeddedResource Include="Changes\Functions\changes-by-doc-map.js" />
    <EmbeddedResource Include="Changes\Functions\synchronizer-indexes-map.js" />
    <EmbeddedResource Include="Changes\Functions\synchronizer-indexes-reduce.js" />
    <EmbeddedResource Include="Commerce\DesignDocs\commerce-reporting.json" />
    <EmbeddedResource Include="Commerce\DesignDocs\commerce.json" />
    <EmbeddedResource Include="Commerce\Functions\invoice-infos-map.js" />
    <EmbeddedResource Include="Commerce\Functions\invoice-payments-map.js" />
    <EmbeddedResource Include="Commerce\Functions\last-purchase-prices-map.js" />
    <EmbeddedResource Include="Commerce\Functions\last-purchase-prices-reduce.js" />
    <EmbeddedResource Include="Common\DesignDocs\common.json" />
    <EmbeddedResource Include="Common\Functions\common-facets-reduce.js" />
    <EmbeddedResource Include="Common\Functions\common-revisions-map.js" />
    <EmbeddedResource Include="CRM\DesignDocs\crm.json" />
    <EmbeddedResource Include="CRM\Functions\partner-actions-map.js" />
    <EmbeddedResource Include="CRM\Functions\partner-balances-by-office-and-id-map.js" />
    <EmbeddedResource Include="CRM\Functions\partner-balances-by-office-map.js" />
    <EmbeddedResource Include="CRM\Functions\partner-balances-partial-invoices.js" />
    <EmbeddedResource Include="CRM\Functions\partner-balances-partial-others.js" />
    <EmbeddedResource Include="CRM\Functions\partner-balances-reduce.js" />
    <EmbeddedResource Include="CRM\Functions\partner-facets-map.js" />
    <EmbeddedResource Include="Enterprise\DesignDocs\enterprise.json" />
    <EmbeddedResource Include="Enterprise\Functions\depository-facets-map.js" />
    <EmbeddedResource Include="Enterprise\Functions\office-facets-map.js" />
    <EmbeddedResource Include="Enterprise\Functions\warehouse-facets-map.js" />
    <EmbeddedResource Include="Finance\Spending\DesignDocs\finance-spending.json" />
    <EmbeddedResource Include="Finance\Spending\Functions\expense-actions-map.js" />
    <EmbeddedResource Include="Finance\Spending\Functions\expense-facets-map.js" />
    <EmbeddedResource Include="FundsManagement\DesignDocs\funds-management.json" />
    <EmbeddedResource Include="FundsManagement\Functions\funds-actions-map.js" />
    <EmbeddedResource Include="FundsManagement\Functions\funds-balances-map.js" />
    <EmbeddedResource Include="FundsManagement\Functions\funds-balances-reduce.js" />
    <EmbeddedResource Include="StockManagement\DesignDocs\stock-management-reporting.json" />
    <EmbeddedResource Include="StockManagement\DesignDocs\stock-management.json" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-by-warehouse-all-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-by-warehouse-and-id-all-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-by-warehouse-and-id-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-by-warehouse-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-partial-consts.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-partial-others.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-partial-overheads.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-partial-transfer-destination.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-actions-partial-transfer-source.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-alternatives-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-balances-by-warehouse-and-id-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-balances-by-warehouse-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-balances-reduce.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-facets-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-info-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-repricing-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-tracking-by-lineId-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-tracking-by-lineSourceId-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-tracking-by-transactionId-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-tracking-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-tracking-partial-consts.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-tracking-partial-transfer-destination.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-tracking-partial-transfer-source.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-turnovers-map.js" />
    <EmbeddedResource Include="StockManagement\Functions\stock-turnovers-reduce.js" />
    <EmbeddedResource Include="StockManagement\Indexes\bucket-info.json" />
    <EmbeddedResource Include="StockManagement\Indexes\stock-search-fts.json" />
    <EmbeddedResource Include="Transactions\DesignDocs\transaction.json" />
    <EmbeddedResource Include="Transactions\Functions\transaction-facets-map.js" />
    <EmbeddedResource Include="Transactions\Functions\transaction-list-map.js" />
    <EmbeddedResource Include="Warehousing\Ordering\DesignDocs\warehousing-ordering.json" />
    <EmbeddedResource Include="Warehousing\Ordering\Functions\stock-orders-map.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="4.9.4" />
    <PackageReference Include="AutoMapper" Version="8.1.1" />
    <PackageReference Include="Castle.Core" Version="4.4.1" />
    <PackageReference Include="CouchbaseNetClient" Version="2.7.27" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mermer.Base\Mermer.csproj" />
    <ProjectReference Include="..\Mermer.Data.Synchronizer.Core.Couch\Mermer.Data.Synchronizer.Core.Couch.csproj" />
    <ProjectReference Include="..\Mermer\Mermer.Main.csproj" />
    <ProjectReference Include="..\Mermer.Core\Mermer.Core.csproj" />
    <ProjectReference Include="..\Mermer.Data.Synchronizer.Core\Mermer.Data.Synchronizer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Couchbase.Linq">
      <HintPath>..\Mermer.Ui.Pc\lib\Couchbase.Linq.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>