version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: mermer_postgres
    restart: always
    environment:
      POSTGRES_DB: payhas
      POSTGRES_USER: payhas_app
      POSTGRES_PASSWORD: payhas_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Mermer.Api/Dockerfile
    container_name: mermer_api
    restart: always
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=payhas;Username=payhas_app;Password=payhas_password
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "5050:8080"

volumes:
  pgdata: