<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>Mermer.Data.Synchronizer.Core</AssemblyName>
    <RootNamespace>Mermer.Data.Synchronizer.Core</RootNamespace>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" Version="4.4.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mermer\Mermer.Main.csproj" />
    <ProjectReference Include="..\Mermer.Core\Mermer.Core.csproj" />
  </ItemGroup>
</Project>