<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Castle.Core" Version="5.2.1" />
    <PackageReference Include="FluentValidation" Version="8.6.3" />
    <PackageReference Include="LinqKit.Core" Version="1.2.11" />
    <PackageReference Include="System.Reflection.TypeExtensions" Version="4.7.0" />
  </ItemGroup>

</Project>