<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWpf>true</UseWpf>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>12.0</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>binyat_icon_003_d85_icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mermer.Base\Mermer.csproj" />
    <ProjectReference Include="..\Mermer\Mermer.Main.csproj" />
    <ProjectReference Include="..\Mermer.Core\Mermer.Core.csproj" />
    <ProjectReference Include="..\Mermer.Mvvm\Mermer.Mvvm.csproj" />
    <ProjectReference Include="..\Mermer.Ui.Core\Mermer.Ui.Core.csproj" />
    <ProjectReference Include="..\Mermer.Ui.Core.Pc\Mermer.Ui.Core.Pc.csproj" />
    <ProjectReference Include="..\Mermer.Data.Patcher\Mermer.Data.Patcher.csproj" />
    <Reference Include="DevExpress.Mvvm.v21.2"><HintPath>lib\DevExpress.Mvvm.v21.2.dll</HintPath></Reference>
    <ProjectReference Include="..\Mermer.Licensing.Client\Mermer.Licensing.Client.csproj" />
    <Reference Include="DevExpress.Mvvm.v21.2">
      <HintPath>lib\DevExpress.Mvvm.v21.2.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Autofac">
      <HintPath>lib\Autofac.dll</HintPath>
    </Reference>
    <Reference Include="Autofac.Extras.MvvmCross">
      <HintPath>lib\Autofac.Extras.MvvmCross.dll</HintPath>
    </Reference>
    <Reference Include="Couchbase.NetClient">
      <HintPath>lib\Couchbase.NetClient.dll</HintPath>
    </Reference>

    <Reference Include="DevExpress.Data.Desktop.v21.2">
      <HintPath>lib\DevExpress.Data.Desktop.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Data.v21.2">
      <HintPath>lib\DevExpress.Data.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.DataAccess.v21.2">
      <HintPath>lib\DevExpress.DataAccess.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Docs.v21.2">
      <HintPath>lib\DevExpress.Docs.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Office.v21.2.Core">
      <HintPath>lib\DevExpress.Office.v21.2.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Printing.v21.2.Core">
      <HintPath>lib\DevExpress.Printing.v21.2.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Spreadsheet.v21.2.Core">
      <HintPath>lib\DevExpress.Spreadsheet.v21.2.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Controls.v21.2">
      <HintPath>lib\DevExpress.Xpf.Controls.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Core.v21.2">
      <HintPath>lib\DevExpress.Xpf.Core.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2">
      <HintPath>lib\DevExpress.Xpf.Grid.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Grid.v21.2.Core">
      <HintPath>lib\DevExpress.Xpf.Grid.v21.2.Core.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.LayoutControl.v21.2">
      <HintPath>lib\DevExpress.Xpf.LayoutControl.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.Printing.v21.2">
      <HintPath>lib\DevExpress.Xpf.Printing.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.Xpf.ReportDesigner.v21.2">
      <HintPath>lib\DevExpress.Xpf.ReportDesigner.v21.2.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.XtraReports.v21.2">
      <HintPath>lib\DevExpress.XtraReports.v21.2.dll</HintPath>
    </Reference>

    <Reference Include="Humanizer">
      <HintPath>lib\Humanizer.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration">
      <HintPath>lib\Microsoft.Extensions.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
      <HintPath>lib\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration.FileExtensions">
      <HintPath>lib\Microsoft.Extensions.Configuration.FileExtensions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration.Json">
      <HintPath>lib\Microsoft.Extensions.Configuration.Json.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Core">
      <HintPath>lib\MvvmCross.Core.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Localization">
      <HintPath>lib\MvvmCross.Localization.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Platform">
      <HintPath>lib\MvvmCross.Platform.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Platform.Wpf">
      <HintPath>lib\MvvmCross.Platform.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Plugins.Messenger">
      <HintPath>lib\MvvmCross.Plugins.Messenger.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Wpf">
      <HintPath>lib\MvvmCross.Wpf.dll</HintPath>
    </Reference>
    <Reference Include="NuGet.Squirrel">
      <HintPath>lib\NuGet.Squirrel.dll</HintPath>
    </Reference>
    <Reference Include="Squirrel">
      <HintPath>lib\Squirrel.dll</HintPath>
    </Reference>

    <Reference Include="Mermer.Core.Couch">
      <HintPath>lib\Mermer.Core.Couch.dll</HintPath>
    </Reference>
    <Reference Include="Mermer.Data.Mapping">
      <HintPath>lib\Mermer.Data.Mapping.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="**\*.png" />
    <Resource Include="**\*.ico" />
    <EmbeddedResource Include="**\*.licenses" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="XamlGeneratedNamespace\" />
  </ItemGroup>
</Project>