<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>12.0</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mermer.Base\Mermer.csproj" />
    <ProjectReference Include="..\Mermer\Mermer.Main.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer" Version="2.14.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MvvmCross.Core">
      <HintPath>..\Mermer.Ui.Pc\lib\MvvmCross.Core.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Platform">
      <HintPath>..\Mermer.Ui.Pc\lib\MvvmCross.Platform.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Localization">
      <HintPath>..\Mermer.Ui.Pc\lib\MvvmCross.Localization.dll</HintPath>
    </Reference>
    <Reference Include="MvvmCross.Plugins.Messenger">
      <HintPath>..\Mermer.Ui.Pc\lib\MvvmCross.Plugins.Messenger.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>