<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mermer.Api</RootNamespace>
    <AssemblyName>Mermer.Api</AssemblyName>
    <UserSecretsId>payhas-binyat-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.*" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mermer.Core\Mermer.Core.csproj" />
    <ProjectReference Include="..\Mermer.Data.Patcher\Mermer.Data.Patcher.csproj" />
    <ProjectReference Include="..\Mermer.Data.Postgres\Mermer.Data.Postgres.csproj" />
    <ProjectReference Include="..\Mermer.Data.Synchronizer.Core.Couch\Mermer.Data.Synchronizer.Core.Couch.csproj" />
    <ProjectReference Include="..\Mermer.Data.Synchronizer.Core\Mermer.Data.Synchronizer.Core.csproj" />
  </ItemGroup>

</Project>
